Repository ioet/time-tracker-backend, pull requests merged in 2020-03, with the labels that each got.

#41 Add dependencies to build
  .dockerignore
  Dockerfile
Labels: bug, enhancement

#42 Update Dockerfile
  Dockerfile
Labels: bug

#45 Add database drivers.
  Dockerfile
Labels: bug

#61 Enable CORS
  requirements/prod.txt
  setup.py
  time_tracker_api/__init__.py
  time_tracker_api/config.py
Labels: enhancement
